version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
  # producer:
  #   container_name: producer
  #   build:
  #     context: ./src
  #     dockerfile: app/producer/producer.dockerfile
  #   volumes:
  #     - ${PWD}:/go/src
  #   command: tail -F /dev/null
  #   restart: on-failure
  #   # depends_on:
  #   #   - rabbitmq
  #   # links: 
  #   #   - rabbitmq
  #   environment:
  #     - module=producer
  # consumer:
  #   container_name: consumer
  #   build:
  #     context: ./src
  #     dockerfile: app/consumer/consumer.dockerfile
  #   command: tail -F /dev/null
  #   volumes:
  #     - ${PWD}/src:/go/src
  #   restart: on-failure
  #   # depends_on:
  #   #   - rabbitmq
  #   # links: 
  #   #   - rabbitmq
  #   environment:
  #     - module=consumer